name: LocalizeRingForHomalg
version: 2017.09.01
date: 01/09/2017
description: A Package for Localization of Polynomial Rings

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/
    - name: Vinay Wagh
      url: http://www.iitg.ernet.in/vinay.wagh/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2013.10.25"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2013.07.12"
      url: "http://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "Modules"
      version: ">= 2017.05.02"
      url: "http://homalg-project.github.io/homalg_project/Modules/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/LocalizeRingForHomalg/
readme: http://homalg-project.github.io/homalg_project/LocalizeRingForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/LocalizeRingForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/LocalizeRingForHomalg-2017.09.01/LocalizeRingForHomalg-2017.09.01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/LocalizeRingForHomalg-2017.09.01/LocalizeRingForHomalg-2017.09.01.zip

abstract: This package is part of the homalg-project and allows localization of a (computable) commutative ring at a (finitely generated) maximal ideal.

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
