name: SCO
version: 2017.09.01
date: 01/09/2017
description: SCO - Simplicial Cohomology of Orbifolds

authors:
    - name: Simon Görtzen
      url: http://wwwb.math.rwth-aachen.de/goertzen

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2011.08.10"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "Modules"
      version: ">= 2011.06.29"
      url: "http://homalg-project.github.io/homalg_project/Modules/"
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/SCO/
readme: http://homalg-project.github.io/homalg_project/SCO/README
packageinfo: http://homalg-project.github.io/homalg_project/SCO/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/SCO-2017.09.01/SCO-2017.09.01.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/SCO-2017.09.01/SCO-2017.09.01.zip

abstract: The <span class="pkgname">SCO</span> package provides functionality to compute simplicial cohomology of orbifolds

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
