name: Gauss
version: 2018.09.08
date: 08/09/2018
description: Extended Gauss functionality for GAP

authors:
    - name: Simon Goertzen
      url: http://wwwb.math.rwth-aachen.de/goertzen

maintainers:
    - name: Mohamed Barakat
      url: http://wwwb.math.rwth-aachen.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">=4.8"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/Gauss/
readme: http://homalg-project.github.io/homalg_project/Gauss/README
packageinfo: http://homalg-project.github.io/homalg_project/Gauss/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/Gauss-2018.09.08/Gauss-2018.09.08.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/Gauss-2018.09.08/Gauss-2018.09.08.zip

abstract: The <span class="pkgname">Gauss</span> package provideds extended Gauss functionality for <span class="pkgname">GAP</span>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
