name: Gauss
version: 2015.10.29
date: 29/10/2015
description: Extended Gauss functionality for GAP

authors:
    - name: Simon Goertzen
      url: http://wwwb.math.rwth-aachen.de/goertzen

maintainers:
    - name: Mohamed Barakat
      url: http://wwwb.math.rwth-aachen.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/

GAP: ">=4.7"

suggested-pkgs:
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/Gauss/
readme: http://homalg-project.github.io/homalg_project/Gauss/README
packageinfo: http://homalg-project.github.io/homalg_project/Gauss/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://homalg-project.github.io/homalg_project/Gauss/Gauss-2015.10.29.tar.gz

abstract: The <span class="pkgname">Gauss</span> package provideds extended Gauss functionality for <span class="pkgname">GAP</span>

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
