markdown:         kramdown
highlighter:      rouge

baseurl:          /homalg_project

include: ['CAP', 'GeneralizedMorphismsForCAP', 'LinearAlgebraForCAP', 'ModulePresentationsForCAP' ]
exclude: [ "index_default.template" ]
