name: ExamplesForHomalg
version: 2018.05.29
date: 29/05/2018
description: Examples for the GAP Package homalg

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Simon Görtzen
      url: http://wwwb.math.rwth-aachen.de/~simon/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/

GAP: ">=4.7"

needed-pkgs:
    - name: "MatricesForHomalg"
      version: ">= 2018.05.29"
      url: "http://homalg-project.github.io/homalg_project/MatricesForHomalg/"
    - name: "HomalgToCAS"
      version: ">= 2011.08.25"
      url: "http://homalg-project.github.io/homalg_project/HomalgToCAS/"
    - name: "RingsForHomalg"
      version: ">= 2017.05.25"
      url: "http://homalg-project.github.io/homalg_project/RingsForHomalg/"
    - name: "Modules"
      version: ">= 2017.05.02"
      url: "http://homalg-project.github.io/homalg_project/Modules/"
    - name: "homalg"
      version: ">= 2015.06.01"
      url: "http://homalg-project.github.io/homalg_project/homalg/"
    - name: "GAPDoc"
      version: ">= 1.1"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: http://homalg-project.github.io/homalg_project/ExamplesForHomalg/
readme: http://homalg-project.github.io/homalg_project/ExamplesForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/ExamplesForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/ExamplesForHomalg-2018.05.29/ExamplesForHomalg-2018.05.29.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/ExamplesForHomalg-2018.05.29/ExamplesForHomalg-2018.05.29.zip

abstract: The <span class="pkgname">ExamplesForHomalg</span> package provides example scripts for the <span class="pkgname">homalg</span> package that can be used with several computer algebra systems

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
