name: ToolsForHomalg
version: 2018.05.22
date: 22/05/2018
description: Special methods and knowledge propagation tools

authors:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/

maintainers:
    - name: Mohamed Barakat
      url: http://www.mathematik.uni-kl.de/~barakat/
    - name: Sebastian Gutsche
      url: http://wwwb.math.rwth-aachen.de/~gutsche/
    - name: Markus Lange-Hegermann
      url: http://wwwb.math.rwth-aachen.de/~markus/

GAP: ">=4.7"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.0"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "AutoDoc"
      version: ">=2013.11.10"
      url: "https://gap-packages.github.io/AutoDoc"

www: http://homalg-project.github.io/homalg_project/ToolsForHomalg/
readme: http://homalg-project.github.io/homalg_project/ToolsForHomalg/README
packageinfo: http://homalg-project.github.io/homalg_project/ToolsForHomalg/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/homalg-project/homalg_project/releases/download/ToolsForHomalg-2018.05.22/ToolsForHomalg-2018.05.22.tar.gz
    - name: .zip
      url: https://github.com/homalg-project/homalg_project/releases/download/ToolsForHomalg-2018.05.22/ToolsForHomalg-2018.05.22.zip

abstract: The <span class="pkgname">ToolsForHomalg</span> package provides GAP extensions for the homalg project

status: deposited
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
